---
-
  name: Install/Update App
  hosts: docker_group
  become: yes
  vars:
  - docker_compose_version: "1.25.0"
  tasks:
    - debug: 
        msg: "Hello Docker"

    - name: "Check if docker is installed"
      shell: command -v docker >/dev/null 2>&1
      register: is_docker_install
      ignore_errors: yes

    - debug: msg="{{is_docker_install}}"

    - name: "Check if docker-compose is installed"
      shell: command -v docker-compose >/dev/null 2>&1
      register: is_docker_compose_install
      ignore_errors: yes

  
    - name: "Add Docker Repository"
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present
      when: is_docker_install.rc != 0

    - name: "Update apt and install docker-ce"
      apt: update_cache=yes name=docker-ce state=latest
      when: is_docker_install.rc != 0

    - name: "Install Docker Module for Python"
      pip:
       name: docker
      when: is_docker_install.rc != 0
      
    - name: "Run and enable docker"
      service:
        name: docker
        state: started
        enabled: true

    - name: "Install docker-compose if necessary"
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes
      when: is_docker_compose_install.rc != 0
      

    - name: "Pull docker image from DockerHub"
      docker_image:
         name: "a21250034cris/my-app:3.0"
         tag: "3.0"
         state: present
         source: pull
    
    - name: "Deploy Docker Compose stack"
      docker_compose:
        project_src: .
