
---
-
  name: Install/Update App
  hosts: server_app
  become: yes
  vars:
  - docker_compose_version: "1.25.0"
  tasks:
    - debug: 
        msg: "Hello Docker"
    - debug: 
        msg: {{my_app_version}}

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: "Install docker.io"
      shell: sudo curl -sSL https://get.docker.com/ | sh
    
    - name: Add group docker to user ansadmin
      user:
        name: ansadmin
        groups: docker
        append: yes
     #- name: "usermod"
     # shell: sudo usermod -aG docker ansadmin
    
    - name: "Run and enable docker"
      service:
        name: docker
        state: started
        enabled: true

    - name: "Check if docker-compose is installed"
      shell: command -v docker-compose >/dev/null 2>&1
      register: is_docker_compose_install
      ignore_errors: yes
    
    - name: "Install docker-compose if necessary"
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes
      when: is_docker_compose_install.rc != 0
    
    - name: "Pull docker image from DockerHub"
      docker_image:
         name: "a21250034cris/my-app:3.0"
         tag: "3.0"
         state: present
         source: pull
    
    - name: "Docker Compose down"
      shell: sudo docker-compose down
    
    - name: "Deploy Docker Compose stack"
      docker_compose:
        project_src: .
